/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommentEnter: typeof import('./src/components/good/CommentEnter.vue')['default']
    CommentInfo: typeof import('./src/components/comment/CommentInfo.vue')['default']
    DownLoadFixed: typeof import('./src/components/DownLoadFixed/DownLoadFixed.vue')['default']
    FocusButton: typeof import('./src/components/good/FocusButton.vue')['default']
    G2PlotRadar: typeof import('./src/components/g2_plot_radar/G2PlotRadar.vue')['default']
    NoComment: typeof import('./src/components/comment/NoComment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopicInfo: typeof import('./src/components/good/TopicInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanImage: typeof import('vant/es')['Image']
    VanPopup: typeof import('vant/es')['Popup']
    VanRate: typeof import('vant/es')['Rate']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    XVanImage: typeof import('./src/components/vant/XVanImage.vue')['default']
  }
}
